import { getCategories } from "../../../services/product.service";

export const headCells: any = [
    {
        id: "image",
        disablePadding: true,
        image: true,
        label: "Product Image",
        props: { align: "left" },
        tableCell: true,
        inputProps: {
            initialValue: '',
            name: "image",
            label: "Product Image",
            type: "image",
            required: true,
        },
    },
    {
        id: "title",
        text: true,
        disablePadding: true,
        label: "Product Name",
        props: {
            align: "left",
        },
        tableCell: true,
        bodyData: true,
        inputType: "text",
        type: "input",
        inputProps: {
            initialValue: '',
            name: "title",
            label: "Title",
            type: "text",
            required: true,
            columnSize: 6,
        },
    },
    {
        id: "description",
        text: true,
        disablePadding: true,
        label: "Description",
        props: {
            align: "left",
        },
        tableCell: true,
        bodyData: true,
        inputType: "text",
        type: "input",
        inputProps: {
            name: "description",
            label: "Description",
            type: "text",
            required: true,
            columnSize: 6,
        },
    },
    {
        id: "price",
        text: true,
        disablePadding: true,
        label: "Price",
        props: {
            align: "left",
        },
        tableCell: true,
        bodyData: true,
        type: "input",
        inputProps: {
            name: "price",
            label: "Price",
            type: "number",
            required: true,
            columnSize: 6,
        },
    },
    {
        id: "price_with_discount",
        text: true,
        disablePadding: true,
        label: "Discount Price",
        props: {
            align: "left",
        },
        tableCell: true,
        bodyData: true,
        type: "input",
        inputProps: {
            name: "price_with_discount",
            label: "Discount Price",
            type: "number",
            required: true,
            columnSize: 6,
        },
    },
    {
        id: "createdAt",
        text: false,
        disablePadding: true,
        date: true,
        label: "Created At",
        props: {
            align: "left",
        },
        tableCell: true,
    },
    {
        id: "category",
        text: false,
        disablePadding: true,
        date: true,
        label: "Created At",
        props: { align: "left" },
        tableCell: false,
        type: "select",
        inputProps: {
            initialValue: '',
            name: "category",
            label: "Category",
            labelField: "title",
            valueField: "_id",
            type: "select",
            required: true,
            fetchFrom: getCategories,
            columnSize: 6,
        },
    },
];
